### PR TITLE
The Big Merge

### PR DESCRIPTION
**Pull request by DLBPointon**
The Final Merge of dev into Main before tagging!

### CODE REVIEW

**Comment by muffato** [comment]
This merge is a "fast-forward" at the git level because the `dev` branch is cleanly attached to to the latest `main`. In other words, the code that would be on `main` after the merge is exactly the same as what's currently on `dev` and has been tested/reviewed in the recent pull-requests.

First check 🤝

**Comment by muffato** [comment]
I ran the full test myself since the run through Tower could not be initiated.

Just checking, @DLBPointon, is it expected that these processes don't have any job ?
- SANGERTOL_TREEVAL:TREEVAL:BUSCO_ANNOTATION:ANCESTRAL_GENE:*
- SANGERTOL_TREEVAL:TREEVAL:LONGREAD_COVERAGE:MINIMAP2_ALIGN_SPLIT
- SANGERTOL_TREEVAL:TREEVAL:SYNTENY:MINIMAP2_ALIGN

**Comment by DLBPointon** [comment]
> I ran the full test myself since the run through Tower could not be initiated.
> 
> Just checking, @DLBPointon, is it expected that these processes don't have any job ?
> 
> * SANGERTOL_TREEVAL:TREEVAL:BUSCO_ANNOTATION:ANCESTRAL_GENE:*
> * SANGERTOL_TREEVAL:TREEVAL:LONGREAD_COVERAGE:MINIMAP2_ALIGN_SPLIT
> * SANGERTOL_TREEVAL:TREEVAL:SYNTENY:MINIMAP2_ALIGN

Hi @muffato,
In these cases (fungi on github and nematode on farm) yes, those 3 processes will not have any jobs.
We only have synteny jobs for birds, align_split is only for genomes > 4gb and Ancestral is only for leps.
Thanks

**Comment by muffato** [comment]
Once #152 is merged, I'm happy to approve this PR

**Review by muffato — APPROVED** [review]

**Pull request merged**
