### PR TITLE
Dp24 tmpfix

### PR DESCRIPTION
**Pull request by DLBPointon**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/treeval/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by weaglesBio — CHANGES_REQUESTED** [review]
I don't know if it has a functional difference but some of the ext.args assignments are wrapped in curly brackets and some are not. Should be updated to be consistent if possible.

I think there is to be a space between -P and the '.' in the FK change. -P takes an argument which is the location to save temp files to.

**Comment by DLBPointon** [comment]
> I don't know if it has a functional difference but some of the ext.args assignments are wrapped in curly brackets and some are not. Should be updated to be consistent if possible.
> 
> I think there is to be a space between -P and the '.' in the FK change. -P takes an argument which is the location to save temp files to.

Thanks for the catch, all fixed and pipeline running. It was the {} in the modules.config that gave an error about being unable to parse the nextflow.config.

**Comment by DLBPointon** [comment]
Now Erroring with bad substitution, will have a look.

**Review by weaglesBio — APPROVED** [review]
Looks okay. Just to confirm we are no longer using the standard pretext snapshot.

**Pull request merged**
