### PR TITLE
Issue 44

### PR DESCRIPTION
**Pull request by weaglesBio**
## PR checklist

- [X] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/treeval/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/treeval _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [X] Make sure your code lints (`nf-core lint`).
- [X] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

Add local modules for mapids and mummer2bed for selfcomp.

### CODE REVIEW

**Review by muffato — COMMENTED** [review]
Nice one ! Two comments on my side:
 - it'd be perfect if you could version the scripts and use that in versions.yml . Examples on how to do that below
 - Why are your `.nf` files executable ? That's unusual

**Comment by priyanka-surana** [comment]
@muffato Is there a way to tell that `.nf` is executable from the PR? I can tell 4 are executable when I download.

**Review by priyanka-surana — COMMENTED** [review]
I agree with @muffato about `versions` and `.nf` being executable. 
Might be good to also add author details at the top of each python script to give credit where due, since this is a group pipeline.

**Comment by muffato** [comment]
It's shown there on the Files tab
Screenshot 2022-12-13 at 10 47 58

**Comment by weaglesBio** [comment]
> Does local testing work? We can try to fix CI testing in a later PR.

Yes, local testing worked.

**Review by priyanka-surana — APPROVED** [review]
LGTM 👍

**Pull request merged**
