### PR TITLE
Dp24 hotfix

### PR DESCRIPTION
**Pull request by DLBPointon**
Removes KMER_READCOVERAGE subworkflow from all places

Fixes to Configs

Fixes to output genome fasta and index

Remove use of temp directory in minimap and samtools

Added Copyright for Arima scripts

### CODE REVIEW

**Comment by DLBPointon** [comment]
This problem is back...
```
Command error:
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  [samfaipath] build FASTA index...
  .command.sh: line 14:    40 Broken pipe             samtools view --reference grTriPseu1.fa -h grTriPseu1_1_hic_bwamem2_merge.bam
          41 Segmentation fault      (core dumped) | PretextMap --sortby nosort --highRes --mapq 0 --memory 3 -o grTriPseu1_1_hr_pi.pretext
```

**Review by weaglesBio — APPROVED** [review]
Looks okay, should be good to merge if the CI testing is not a blocker.

**Comment by yumisims** [comment]
@gq1 @muffato we have encountered this Segmentation fault on pretext recently. I have tried changing nf version on ci but still no luck. The error only happens when doing ci test and not on the farm and elsewhere. I wonder if it is because the ubuntu server version caused that? Thanks

**Comment by yumisims** [comment]
resolved, please merge.

**Review by yumisims — APPROVED** [review]
looks good

**Pull request merged**
