### PR TITLE
Dp24 fix genomesub

### PR DESCRIPTION
**Pull request by DLBPointon**
Adding a missing line in the RAPID and RAPID-TOL workflows.

### CODE REVIEW

**Review by weaglesBio — APPROVED** [review]

**Review by weaglesBio — CHANGES_REQUESTED** [review]
There is not a GNU_SORT for unsorted, need to use CUSTOM_GETCHROMSIZES

**Review by weaglesBio — COMMENTED** [review]
Can this include the discussed updates to the memory resources for:
CRAM_FILTER_ALIGN_BWAMEM2_FIXMATE_SORT
CRAM_FILTER_MINIMAP2_FILTER5END_FIXMATE_SORT
FKUTILS_FKPROF

**Comment by yumisims** [comment]
CRAM_FILTER_ALIGN_BWAMEM2_FIXMATE_SORT
CRAM_FILTER_MINIMAP2_FILTER5END_FIXMATE_SORT
FKUTILS_FKPROF 
should already in

**Comment by DLBPointon** [comment]
I've added it now, i must have removed it whilst messing around with the resources earlier.

**Review by weaglesBio — APPROVED** [review]

**Review by weaglesBio — CHANGES_REQUESTED** [review]
These are duplicated, rather than replacing. Can be removed, change already present in galaxy_dev.

**Pull request merged**
