### PR TITLE
Update to the deault github runner

### PR DESCRIPTION
**Pull request by gq1**
change to the default runner for now.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/treeval/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by gq1** [comment]
@yumisims @DLBPointon 
Do we have the following step in the rapid test before? I remember the rapid test can pass when using the Github default runner.
`RAPID:SANGERTOL_TREEVAL_RAPID:TREEVAL_RAPID:HIC_MAPPING:JUICER_TOOLS_PRE `

There is java process asking for 36G memory directly. Can we try `java -Xms1g -Xmx36g`?

**Comment by DLBPointon** [comment]
Hi Guoying, sorry for taking my time getting back to you. I've been on holiday.

> @yumisims @DLBPointon Do we have the following step in the rapid test before? I remember the rapid test can pass when using the Github default runner. `RAPID:SANGERTOL_TREEVAL_RAPID:TREEVAL_RAPID:HIC_MAPPING:JUICER_TOOLS_PRE `

The process was in there. However, it was coded to not run on the GitHub runner due to the sheer amount of resources the process needs. I thought the runner was to still get the tiny test working properly and then a large run on the farm. If not then I can add the full test back in, but Tiny will also need the custom runner.

> There is java process asking for 36G memory directly. Can we try `java -Xms1g -Xmx36g`?

We can indeed try this.

**Comment by yumisims** [comment]
> Hi Guoying, sorry for taking my time getting back to you. I've been on holiday.
> 
> > @yumisims @DLBPointon Do we have the following step in the rapid test before? I remember the rapid test can pass when using the Github default runner. `RAPID:SANGERTOL_TREEVAL_RAPID:TREEVAL_RAPID:HIC_MAPPING:JUICER_TOOLS_PRE `
> 
> The process was in there. However, it was coded to not run on the GitHub runner due to the sheer amount of resources the process needs. I thought the runner was to still get the tiny test working properly and then a large run on the farm. If not then I can add the full test back in, but Tiny will also need the custom runner.
> 
> > There is java process asking for 36G memory directly. Can we try `java -Xms1g -Xmx36g`?
> 
> We can indeed try this.

@DLBPointon  need Will @weaglesBio  to update the juicer part first. then we could minimize the heap, I am thinking to optimise the other resource a bit, these should resolve the testing problem.

**Comment by DLBPointon** [comment]
> @DLBPointon need Will @weaglesBio to update the juicer part first. then we could minimize the heap, I am thinking to optimise the other resource a bit, these should resolve the testing problem.

Sure ok.

I'll get some decent graphs going.

**Review by yumisims — APPROVED** [review]
rapid testing passed, we will open another branch to carry out full test. Thanks @gq1 @DLBPointon @muffato

**Pull request merged**
